name: any_chat
description: 'Anonymous chat application'
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  dio: ^5.6.0
  flutter_riverpod: ^2.5.1
  freezed: ^2.5.7
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  cupertino_icons: ^1.0.8
  fpdart: ^1.1.0
  fast_immutable_collections: ^10.2.4
  collection: ^1.18.0
  intl: ^0.19.0
  async: ^2.11.0
  pretty_dio_logger: ^1.4.0
  logger: ^2.4.0
  get_it: ^8.0.1
  sqlite_async: ^0.9.0
  web_socket_channel: ^3.0.1
  connectivity_plus: ^6.1.0
  stream_transform: ^2.1.0
  tuple: ^2.0.2
  quiver: ^3.2.2
  rx_shared_preferences: ^4.0.0
  rxdart: ^0.28.0
  scroll_to_index: ^3.0.1

  super_paging:
    git: https://github.com/dinaraparanid/super_paging.git

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.12
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/